# Generated by Django 3.2.8 on 2021-10-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='profile',
        ),
    ]
