# Generated by Django 3.2.8 on 2021-10-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.dish'),
        ),
    ]
