# Generated by Django 3.2.8 on 2021-10-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_discount_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
