# Generated by Django 3.2.8 on 2021-10-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dish_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
