# Generated by Django 3.2.8 on 2021-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_dish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in process', 'In process'), ('ready', 'Ready'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=25),
        ),
    ]
