# Generated by Django 3.2.8 on 2021-10-10 18:20

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
