# Generated by Django 3.2.8 on 2021-10-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='level',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tree_id',
        ),
    ]
