# Generated by Django 3.2.8 on 2021-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20211010_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
